"""Constants for the NetX Thermostat integration."""

DOMAIN = "netx_thermostat"

# Default connection settings
DEFAULT_PORT = 10001
CONNECTION_TIMEOUT = 10
COMMAND_TIMEOUT = 5

# Update interval in seconds
UPDATE_INTERVAL = 30

# Temperature limits
MIN_TEMP_HEAT = 35
MAX_TEMP_HEAT = 89
MIN_TEMP_COOL = 42
MAX_TEMP_COOL = 90
MIN_TEMP = 35
MAX_TEMP = 90

# Humidity limits
MIN_HUMIDITY_SETPOINT = 10
MAX_HUMIDITY_SETPOINT = 90
MIN_HUMIDITY_VARIANCE = 2
MAX_HUMIDITY_VARIANCE = 10

# API Commands - Read
CMD_LOGIN = "WMLS1D"
CMD_GET_TEMP_SCALE = "RTS1"
CMD_GET_ALL_STATES = "RAS1"
CMD_GET_HUMIDITY = "RRHS1"
CMD_GET_OPERATION_MODE = "RNS1"
CMD_GET_RELAY_MODE = "RMRF1"
CMD_GET_HUMIDIFICATION = "RMHS1"
CMD_GET_DEHUMIDIFICATION = "RMDHS1"
CMD_GET_RELAY_STATE = "RRS1"
CMD_GET_SYSTEM_STATE = "RSS1"

# API Commands - Write (Manual Mode)
CMD_SET_MODE_MANUAL = "WNMS1D"
CMD_SET_FAN_MANUAL = "WNFM1D"
CMD_SET_COOL_MANUAL = "WNCD1D"
CMD_SET_HEAT_MANUAL = "WNHD1D"

# API Commands - Write (Schedule Mode)
CMD_SET_MODE_SCHEDULE = "WMS1D"
CMD_SET_FAN_SCHEDULE = "WFM1D"
CMD_SET_COOL_SCHEDULE = "WOC1D"
CMD_SET_HEAT_SCHEDULE = "WOH1D"

# API Commands - Write (General)
CMD_SET_TEMP_SCALE = "WTS1D"
CMD_SET_RELAY_MODE = "WMRF1D"
CMD_SET_HUMIDIFICATION = "WMHS1D"
CMD_SET_DEHUMIDIFICATION = "WMDHS1D"

# HVAC Modes
HVAC_MODE_OFF = "OFF"
HVAC_MODE_HEAT = "HEAT"
HVAC_MODE_COOL = "COOL"
HVAC_MODE_AUTO = "AUTO"

# Fan Modes
FAN_MODE_AUTO = "AUTO"
FAN_MODE_ON = "ON"

# Operation Modes
OPERATION_MODE_MANUAL = "ON"
OPERATION_MODE_SCHEDULE = "OFF"

# Humidity Control Modes
HUMIDITY_WITH_HEATING = "WH"
HUMIDITY_INDEPENDENT_HEATING = "IH"
HUMIDITY_WITH_COOLING = "WC"
HUMIDITY_INDEPENDENT_COOLING = "IC"

# Humidity Relay Modes (for preset_mode)
RELAY_MODE_OFF = "OFF"
RELAY_MODE_HUM = "HUM"
RELAY_MODE_DEHUM = "DEHUM"

# Preset mode mapping
PRESET_NONE = "none"
PRESET_HUMIDIFY = "Humidify"
PRESET_DEHUMIDIFY = "Dehumidify"

PRESET_TO_RELAY = {
    PRESET_NONE: RELAY_MODE_OFF,
    PRESET_HUMIDIFY: RELAY_MODE_HUM,
    PRESET_DEHUMIDIFY: RELAY_MODE_DEHUM,
}

RELAY_TO_PRESET = {
    RELAY_MODE_OFF: PRESET_NONE,
    RELAY_MODE_HUM: PRESET_HUMIDIFY,
    RELAY_MODE_DEHUM: PRESET_DEHUMIDIFY,
}

# Response prefixes
RESP_LOGIN_OK = "OK"
RESP_TEMP_SCALE = "RTS1:"
RESP_ALL_STATES = "RAS1:"
RESP_HUMIDITY = "RRHS1:"
RESP_OPERATION_MODE = "RNS1:"
RESP_RELAY_MODE = "RMRF1:"
RESP_HUMIDIFICATION = "RMHS1:"
RESP_DEHUMIDIFICATION = "RMDHS1:"
RESP_RELAY_STATE = "RRS1:"
RESP_SYSTEM_STATE = "RSS1:"
